[package]
name = "cheese_wheel"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mouce = "0.2.43"
winapi = { version = "0.3.9", features = ["winuser", "windef", "winnt", "ntdef", "minwindef"] }
